baseURL = 'https://alpha-ρ.org'
languageCode = 'en-us'
title = 'alpha-ρ'
theme = 'PaperMod'

[params]
    description = "A comprehensive ecosystem of scientific software tools for proteomics research and mass spectrometry data analysis"
    author = "MannLabs"
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    UseHugoToc = true
    disableSpecial1stPost = false
    disableScrollToTop = false
    comments = false
    hidemeta = false
    hideSummary = false
    showtoc = false
    tocopen = false

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/MannLabs"

    [params.assets]
        favicon = "/favicon.ico"
        favicon16x16 = "/favicon-16x16.png"
        favicon32x32 = "/favicon-32x32.png"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 10

    [[menu.main]]
        identifier = "packages"
        name = "Packages"
        url = "/packages/"
        weight = 20

    [[menu.main]]
        identifier = "mission"
        name = "Mission"
        url = "/mission/"
        weight = 30
    
    [[menu.main]]
        identifier = "news"
        name = "News"
        url = "/news/"
        weight = 40
    [[menu.main]]
        identifier = "community"
        name = "Community"
        url = "/community/"
        weight = 50

    [[menu.main]]
        identifier = "contributors"
        name = "Contributors"
        url = "/contributors/"
        parent = "community"
        weight = 10

    [[menu.main]]
        identifier = "guidelines"
        name = "Guidelines"
        url = "/guidelines/"
        parent = "community"
        weight = 20
[markup]
    [markup.highlight]
        style = "github"
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 2
